# .github/workflows/ci.yml

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events to the main branch.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "typecheck".
  typecheck:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sets up the specified version of Node.js.
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # You can adjust this to your project's Node.js version.

      # Forcefully remove old dependencies, package-lock, and cache to ensure a clean slate.
      - name: Clean dependencies and lockfile
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm package-lock.json

      # Installs dependencies using a clean-install to ensure a fresh dependency tree.
      - name: Install dependencies
        run: npm ci

      # Runs the 'typecheck' task using Turbo, forcing a fresh build.
      - name: Run typecheck with cache bypass
        run: TURBO_FORCE=true npx turbo run typecheck --filter=portal
