# .github/workflows/ci.yml

name: CI

# Triggers the workflow on push or pull request events to the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A single job to build and test the project.
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Run the typecheck and build steps.
      - name: Run typecheck
        run: npx turbo run typecheck --filter=portal

      - name: Run build
        run: npx turbo run build --filter=portal
